site_name: EasySort Documentation
repo_url: https://github.com/EasySort/easysort
site_url: https://docs.easysort.org
site_description: Documentation for EasySort - An open-source waste sorting system
site_author: EasySort Team

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - toc.follow
  palette:
    # Light mode
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: black
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - attr_list
  - md_in_html

nav:
  - GETTING STARTED:
    - index.md
    - Quick-start: getting-started/quick-start.md
  - ABOUT EASYSORT:
    - Our Mission: why/mission.md
    - Waste Landscape: why/landscape.md
    - Market Players: why/competitors.md
    - Industry Funding: why/funding.md
  - THE SOLUTION:
    - What we offer: products/index.md
  - CONTRIBUTING:
    - How to contribute: contributing/index.md
    - Our projects: contributing/projects.md
    - Our current priorities: contributing/plan-for-victory.md
    - What we still don't know: contributing/open-questions.md
  - LINKS:
    - Website: https://easysort.org
    - Github: https://github.com/easysort