indent-width = 4
preview = true
target-version = "py310"

lint.select = [
  "E4", "E7", "E9", "F",  # default
  "UP039",  # unnecessary-class-parentheses
  "C416",   # unnecessary-comprehension
  "RET506", # superfluous-else-raise
  "RET507", # superfluous-else-continue
  "A",      # builtin-variable-shadowing, builtin-argument-shadowing, builtin-attribute-shadowing
  "SIM105", # suppressible-exception
  "FURB110",# if-exp-instead-of-or-operator
  "RUF018", # assignment-in-assert
  "I",      # isort
]

line-length = 120

exclude = [
  "docs/",
  "examples/",
  "extra/",
  "tinygrad/",
]
