name: build-and-deploy-docs

on:
  push:
    branches: [ main ]          # rebuild on every push to main
  workflow_dispatch:            # manual trigger button

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with: { python-version: '3.x' }

      - name: Install MkDocs
        run:  pip install mkdocs mkdocs-material

      - name: Deploy to gh-pages
        run:  mkdocs gh-deploy --force --clean     # builds + pushes
