name: Lint

on:
  pull_request:
    branches: [ main ]  # or master, depending on your default branch
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # adjust version as needed

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff mypy pylint pytest

      - name: Run Ruff
        run: python -m ruff check easysort/ tests/ --fix

      - name: Run MyPy
        run: python -m mypy easysort/ --strict-equality --follow-imports=silent

      - name: Run Tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: python -m pytest tests/

      - name: Run Pylint
        run: python -m pylint easysort/ 